# api-gateway.yml - Simple and reliable (APIs only)
# Location: C:\Anshul\Documents\Work\Antra\code\springboot-microservices\config-repo\api-gateway.yml

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Employee API
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees(?<segment>/?.*), /api/v1/employees${segment}

        # Department API
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - RewritePath=/departments(?<segment>/?.*), /api/v1/departments${segment}
