# department-service.yml - Exactly from your original application.yml
# Location: C:\Anshul\Documents\Work\Antra\code\springboot-microservices\config-repo\department-service.yml

spring:
  application:
    name: DEPARTMENT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: department
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: department
    default-schema: department
    table: flyway_schema_history_departments
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true

server:
  port: 8082

logging:
  pattern:
    console: "[%X{traceId:-NO_TRACE}] %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "[%X{traceId:-NO_TRACE}] %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    com.example.department: DEBUG
    org.springframework.web: INFO