spring:
  application:
    name: EMPLOYEE-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: employee
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: employee
    default-schema: employee
    table: flyway_schema_history_employees
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true

server:
  port: 8081

logging:
  pattern:
    console: "[%X{traceId:-NO_TRACE}] %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "[%X{traceId:-NO_TRACE}] %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    com.example.employee: DEBUG
    org.springframework.web: INFO